version: '3'
services:    
  api:
    build:
      dockerfile: Dockerfile
      context: ./us-store-api
    volumes:
      - /app/node_modules
      - ./us-store-api:/app
  graphql:
    build:
      dockerfile: Dockerfile
      context: ./us-store-graphql
    volumes:
      - /app/node_modules
      - ./us-store-graphql:/app
    depends_on:
      - api
 
  web:
    build:
      dockerfile: Dockerfile
      context: ./us-store-web
    volumes:
      - /app/node_modules
      - ./us-store-web:/app
      - ./us-store-web/.next:/app/.next    
    depends_on:
      - graphql    
  
  reverse-proxy:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./us-store-reverse-proxy
    ports:
      - '80:80'
    depends_on:      
      - graphql
      # - web