version: '3'
services:    
  api:
    build:
      dockerfile: Dockerfile
      context: ./domain-services/user-api
    volumes:
      - /app/node_modules
      - ./domain-services/user-api:/app
    networks:
      - my-net

  spinner1:
    build:
      dockerfile: Dockerfile
      context: ./graphql/users-spinner
    volumes:
      - /app/node_modules
      - ./graphql/users-spinner:/app
    depends_on:
      - api
    networks:
      - my-net

  spinner2:
    build:
      dockerfile: Dockerfile
      context: ./graphql/posts-spinner
    volumes:
      - /app/node_modules
      - ./graphql/posts-spinner:/app
    depends_on:
      - api
    networks:
      - my-net
  
  graphql:
    build:
      dockerfile: Dockerfile
      context: ./graphql/federated-gateway
    volumes:
      - /app/node_modules
      - ./graphql/federated-gateway:/app
    depends_on:
      - spinner1
      - spinner2
    networks:
      - my-net
 
  web:
    build:
      dockerfile: Dockerfile
      context: ./web
    volumes:
      - /app/node_modules
      - ./web:/app
      - ./web/.next:/app/.next    
    depends_on:
      - graphql  
    networks:
      - my-net
  
  reverse-proxy:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./reverse-proxy
    ports:
      - '80:80'
    depends_on:        
      - graphql
      - web
    networks:
      - my-net
  
networks:
  my-net:
